apiVersion: v2
name: singbox-operator
description: A Kubernetes Operator for sing-box proxy configuration orchestration
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - proxy
  - sing-box
  - operator
home: https://github.com/shlande/singbox-operator
sources:
  - https://github.com/shlande/singbox-operator
maintainers:
  - name: singbox-operator maintainers
