apiVersion: singboxoperator.shlande.top/v1alpha1
kind: User
metadata:
  name: user-alice
  namespace: default
spec:
  protocol: vless
  authSecret:
    name: user-alice-secret
    namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: user-alice-secret
  namespace: default
stringData:
  uuid: "550e8400-e29b-41d4-a716-446655440000"
