---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - singboxoperator.shlande.top
  resources:
  - usergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - singboxoperator.shlande.top
  resources:
  - usergroups/finalizers
  verbs:
  - update
- apiGroups:
  - singboxoperator.shlande.top
  resources:
  - usergroups/status
  verbs:
  - get
  - patch
  - update
