apiVersion: singboxoperator.shlande.top/v1alpha1
kind: UserGroup
metadata:
  labels:
    app.kubernetes.io/name: sing-box-operator-2
    app.kubernetes.io/managed-by: kustomize
  name: usergroup-sample
spec:
  # TODO(user): Add fields here
