{{- if and .Values.webhook.enabled .Values.certManager.enabled }}
{{- $issuerName := ternary (printf "%s-selfsigned-issuer" (include "singbox-operator.fullname" .)) .Values.certManager.issuerName .Values.certManager.createIssuer }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "singbox-operator.fullname" . }}-webhook-server-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "singbox-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - {{ include "singbox-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
  - {{ include "singbox-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: {{ .Values.certManager.issuerKind }}
    name: {{ $issuerName }}
  secretName: {{ include "singbox-operator.fullname" . }}-webhook-server-cert
{{- end }}
